food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('<int:pk>/', views.DetailClassView.as_view(), name='prod_details'),
    path('add_item/', views.AddClassView.as_view(), name='add_item'),
    path('update_item/<int:pk>/', views.UpdateClassView.as_view(), name='update_item'),
    path('delete_item/<int:pk>/', views.DeleteClassView.as_view(), name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.RegisterClassView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ProfileData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='man.png',
                              upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django.forms import ModelForm
from food.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = "__all__"

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class Signup(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from .models import Item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


# Create your views here.
class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class DetailClassView(DetailView):
    model = Item
    template_name = 'food/details.html'


class AddClassView(CreateView):
    model = Item
    template_name = 'food/add_item_form.html'
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    
    def form_valid(self, form):
        form.instance.username = self.request.user
        return super().form_valid(form)
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    


class UpdateClassView(UpdateView):
    model = Item
    template_name = 'food/add_item_form.html'
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    success_url = reverse_lazy('food:index')


class DeleteClassView(DeleteView):
    model = Item
    template_name = 'food/delete_item.html'
    success_url = reverse_lazy('food:index')

users/views.py
from django.shortcuts import render,redirect
from .forms import Signup
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from .forms import Signup
from django.urls import reverse_lazy
from .models import ProfileData

# Create your views here.
class RegisterClassView(CreateView):
    model = ProfileData
    form_class = Signup
    success_url = reverse_lazy('login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Account successfuly created')
        return response


def logout_view(request):
    logout(request)
    return redirect('login')


@login_required
def profilepage(request):
    return render(request, 'profile.html')

food/templates/food/add_item_form.html
{% extends 'food/base.html' %}

{% block title %}Add Food{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-7 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h3 class="h3"><i>Enter food details below</i></h3>
                    </div>
                </div>
                <div class="card-body offset-md-2">
                    <form action="#" method="POST" class="form">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <b><i>{{ form.item_name.label }}</i></b>
                            <div class="form-group">
                                {{ form.item_name }}
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <b><i>{{ form.item_desc.label }}</i></b>
                            <div class="form-group">
                                {{ form.item_desc }}
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <b><i>{{ form.item_price.label }}</i></b>
                            <div class="form-group">
                                {{ form.item_price }}
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <b><i>{{ form.item_image.label }}</i></b>
                            <div class="form-group">
                                {{ form.item_image }}
                            </div>
                        </div>
                        <div>
                        <button type="submit" class="btn btn-primary"><b><i>Submit</i></b></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'food/styles.css' %}"/>
    <link href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAADAwoA////AFRUlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEREREREREREREREREiIhEREREREiICAREREREQICIhERERERICICEREREREiIiIRERERERICIRERERERERERERERERERERERESIiEREREREQIgIhERERERIiIiEREREREiAiARERERERIiAREREREREREREREREREREREREREREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" rel="icon" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body class="bg-primary-subtle">
    <header class="p-3 text-bg-dark">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-start justify-content-lg-start">
          <a href="#" class="nav-link px-2 text-white"><h2 class="h2"><i>foodie</i></h2></a>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'food:index' %}" class="nav-link px-2 text-blue"><b><i>home</i></b></a></li>
            <li><a href="{% url 'food:add_item' %}" class="nav-link px-2 text-blue"><b><i>addfood</i></b></a></li>
          </ul>
          <div class="text-end">
              {% if user.is_authenticated %}
              <a href="{% url 'logout' %}"><button type="button" class="btn btn-outline-light me-2">Logout</button></a>
              <a href="{% url 'profile' %}"><button type="button" class="btn bg-primary-subtle"><b><i>{{ user.username }}</i></b></button></a>
              {% else %}
              <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
              <a href="{% url 'register' %}"><button type="button" class="btn btn-info">Signup</button></a>
              {% endif %}
          </div>
        </div>
      </div>
    </header>

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-success d-flex alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
      {% endfor %} 
    {% endif %} 
    
    {% block content %}
    {% endblock %}
  </body>
</html>

food/templates/food/delete_item.html
{% extends 'food/base.html' %}

{% block title %}Delete Food{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h5>Do you want to delete {{ item.item_name }}</h5>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock %}

food/templates/food/details.html
{% extends 'food/base.html' %} 
{% block title %}Details{% endblock %} 


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-2 mt-3">
      <img src="{{ item.item_image }}" alt="{{item.item_name}}" class="card" height="150px" width="300px"/>
    </div>
    <div class="col-md-6 mt-3">
      <div class="d-flex align-items-center justify-content-center">
        <h3 class="h3 small"><b>{{ object.item_name }}</b></h3>
      </div>
      <div class="d-flex align-items-center justify-content-center">
        <h6 class="h6 small"><i>{{ object.item_desc }}</i></h6>
      </div>
      <a href="{% url 'food:delete_item' item.id %}" class="btn btn-outline-danger"><b><i>Delete</i></b></a>
    </div>
  </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %} 
{% block title %}Home{% endblock %} 
{% block content %} 
{% for object in item_list %}
  <div class="row">
    <div class="col-md-2 offset-md-2 mb-3 mt-2">
      <img src="{{ object.item_image }}" height="75px" width="150px" class="card" alt="pizza image"/>
    </div>
    <div class="col-md-2 mt-3">
      <h1 class="h1 small"><b>{{ object.item_name }}</b></h1>
      <h2 class="h2 small"><i>${{ object.item_price }}</i></h4>
      <h3 class="h3 small"><em>Posted by: {{ object.username }}</em></h4>
    </div>
    <div class="col-md-2 mt-5">
      <a href="{% url 'food:prod_details' object.id %}" class="btn btn-success"><b><i>Details</i></b></a>
      <a href="{% url 'food:update_item' object.id %}" class="btn btn-outline-warning text-black"><b><i>Update</i></b></a>
    </div>
  </div>
{% endfor %} 

{% endblock %}